//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ConnectionRequest.msg.
//

#ifndef __CONNECTIONREQUEST_M_H
#define __CONNECTIONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ConnectionRequest;
/**
 * Class generated from <tt>ConnectionRequest.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet ConnectionRequest
 * {
 *     bool ConnectionEnabled;
 *     int WindowSize;
 * }
 * </pre>
 */
class ConnectionRequest : public ::omnetpp::cPacket
{
  protected:
    bool ConnectionEnabled = false;
    int WindowSize = 0;

  private:
    void copy(const ConnectionRequest& other);

  protected:
    bool operator==(const ConnectionRequest&) = delete;

  public:
    ConnectionRequest(const char *name=nullptr, short kind=0);
    ConnectionRequest(const ConnectionRequest& other);
    virtual ~ConnectionRequest();
    ConnectionRequest& operator=(const ConnectionRequest& other);
    virtual ConnectionRequest *dup() const override {return new ConnectionRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getConnectionEnabled() const;
    virtual void setConnectionEnabled(bool ConnectionEnabled);

    virtual int getWindowSize() const;
    virtual void setWindowSize(int WindowSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConnectionRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConnectionRequest& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ConnectionRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<ConnectionRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONNECTIONREQUEST_M_H

