(function(g){var window=this;'use strict';var DA=function(l,y){g.n.call(this,{U:"button",RI:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],Y:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},T:[{U:"svg",Y:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},T:[{U:"g",Y:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},T:[{U:"g",Y:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
T:[{U:"path",Y:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.V=l;this.listen("click",this.onClick,this);this.updateValue("title",g.ZO(l,"Expandir","i"));this.update({"data-title-no-tooltip":"Expandir"});this.addOnDisposeCallback(g.ht(y.hf(),this.element))},cnB=function(l){g.n.call(this,
{U:"div",
Z:"ytp-miniplayer-ui"});this.L=!1;this.player=l;this.S(l,"minimized",this.Cf);this.S(l,"onStateChange",this.xgT);this.S(l,"documentpictureinpicturechange",this.Sy9)},Otb=function(l,y){g.Er(l.player.getRootNode(),"ytp-player-minimized",y)},HtH=function(l){g.IG.call(this,l);
this.K=new g.n4(this);this.G=new cnB(this.player);this.G.hide();g.wQ(this.player,this.G.element,4);l.isMinimized()&&(this.load(),g.Er(l.getRootNode(),"ytp-player-minimized",!0))};
g.M(DA,g.n);DA.prototype.onClick=function(){this.V.HT("onExpandMiniplayer")};g.M(cnB,g.n);g.C=cnB.prototype;
g.C.show=function(){this.G=new g.la(this.BS,null,this);this.G.start();if(!this.L){this.tooltip=new g.o5(this.player,this);g.Q(this,this.tooltip);g.wQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.gX=new g.km(this.player);g.Q(this,this.gX);this.progressBar=new g.Pa(this.player,this);g.Q(this,this.progressBar);g.wQ(this.player,this.progressBar.element,4);this.K=new g.n({U:"div",Z:"ytp-miniplayer-scrim"});g.Q(this,this.K);this.K.k7(this.element);this.S(this.K.element,"click",this.mW);
var l=new g.n({U:"button",RI:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Cerrar"},T:[g.JI()]});g.Q(this,l);l.k7(this.K.element);this.S(l.element,"click",this.Aa);l=new DA(this.player,this);g.Q(this,l);l.k7(this.K.element);this.N=new g.n({U:"div",Z:"ytp-miniplayer-controls"});g.Q(this,this.N);this.N.k7(this.K.element);this.S(this.N.element,"click",this.mW);var y=new g.n({U:"div",Z:"ytp-miniplayer-button-container"});g.Q(this,y);y.k7(this.N.element);l=new g.n({U:"div",Z:"ytp-miniplayer-play-button-container"});
g.Q(this,l);l.k7(this.N.element);var r=new g.n({U:"div",Z:"ytp-miniplayer-button-container"});g.Q(this,r);r.k7(this.N.element);this.W=new g.d3(this.player,this,!1);g.Q(this,this.W);this.W.k7(y.element);y=new g.DU(this.player,this);g.Q(this,y);y.k7(l.element);this.nextButton=new g.d3(this.player,this,!0);g.Q(this,this.nextButton);this.nextButton.k7(r.element);this.J=new g.KA(this.player,this,0);g.Q(this,this.J);this.J.k7(this.K.element);this.B=new g.n({U:"div",Z:"ytp-miniplayer-buttons"});g.Q(this,
this.B);g.wQ(this.player,this.B.element,4);l=new g.n({U:"button",RI:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Cerrar"},T:[g.JI()]});g.Q(this,l);l.k7(this.B.element);this.S(l.element,"click",this.Aa);l=new g.n({U:"button",RI:["ytp-miniplayer-replay-button","ytp-button"],Y:{"aria-label":"Cerrar"},T:[g.Bb()]});g.Q(this,l);l.k7(this.B.element);this.S(l.element,"click",this.yfq);l=new DA(this.player,this);g.Q(this,l);l.k7(this.B.element);this.S(this.player,"presentingplayerstatechange",
this.UJ);this.S(this.player,"appresize",this.uT);this.S(this.player,"fullscreentoggled",this.uT);this.uT();this.L=!0}this.player.getPlayerState()!==0&&g.n.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.C.hide=function(){this.G&&(this.G.dispose(),this.G=void 0);g.n.prototype.hide.call(this);this.player.isMinimized()||(this.L&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.C.yr=function(){this.G&&(this.G.dispose(),this.G=void 0);g.n.prototype.yr.call(this)};
g.C.Aa=function(){this.player.j("kevlar_watch_while_v2")||this.player.stopVideo();this.player.HT("onCloseMiniplayer")};
g.C.yfq=function(){this.player.playVideo()};
g.C.mW=function(l){if(l.target===this.K.element||l.target===this.N.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.C.Cf=function(){Otb(this,this.player.isMinimized())};
g.C.Sy9=function(){Otb(this,this.player.oa());g.Er(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.oa())};
g.C.Zj=function(){this.progressBar.Rd();this.J.Rd()};
g.C.BS=function(){this.Zj();this.G&&this.G.start()};
g.C.UJ=function(l){g.b(l.state,32)&&this.tooltip.hide()};
g.C.uT=function(){var l=this.player.TD().getPlayerSize().width;g.IQd(this.progressBar,0,l,!1);g.xW(this.progressBar)};
g.C.xgT=function(l){this.player.isMinimized()&&(l===0?this.hide():this.show())};
g.C.hf=function(){return this.tooltip};
g.C.j1=function(l,y,r,c,O){var H=0,V=0,T=0,f=g.hH(l);c=y&&(g.fU(y,"ytp-prev-button")||g.fU(y,"ytp-next-button"));if(y){r=g.fU(y,"ytp-play-button");var N=g.fU(y,"ytp-miniplayer-expand-watch-page-button");c?H=T=12:r?(y=g.JH(y,this.element),T=y.x,H=y.y-12):N&&(T=g.fU(y,"ytp-miniplayer-button-top-left"),H=g.JH(y,this.element),y=g.hH(y),T?(T=8,H=H.y+40):(T=H.x-f.width+y.width,H=H.y-20))}else T=r-f.width/2,V=25+(O||0);y=this.player.TD().getPlayerSize();O=H+(O||0);f=g.Sx(T,0,y.width-f.width-12);O?(l.style.top=
O+"px",l.style.bottom=""):(l.style.top="",l.style.bottom=V+"px");l.style.left=f+"px";V=g.fU(l,"ytp-preview");l.style.visibility=c&&V&&y.height<225?"hidden":""};g.M(HtH,g.IG);g.C=HtH.prototype;g.C.onVideoDataChange=function(){if(this.player.getVideoData()){var l=this.player.getVideoAspectRatio(),y=16/9;l=l>y+.1||l<y-.1;g.Er(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",l)}};
g.C.create=function(){g.IG.prototype.create.call(this);this.K.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.C.bV=function(){return!1};
g.C.load=function(){this.player.hideControls();this.G.show()};
g.C.unload=function(){this.player.showControls();this.G.hide()};g.K8("miniplayer",HtH);})(_yt_player);
